# This is a basic workflow that is manually triggered

name: AutoMailor workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Python3.8
      uses: actions/setup-python@v2
      with: python-version: 3.8

    # Runs a single command using the runners shell
    - name: Setup environment
      run: python -m pip install lxml 

    - name: Run AutoMailor
      run: python main.py
