# This is a basic workflow that is manually triggered

name: AutoMailor workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
    schedule:
    ## '[min] [hour] [day] [month] [weekday]'
    - cron: '0 12 * * *'
      ## at the begin of every hour
   
env: 
  GITHUB_NAME: bon-qi
  GITHUB_EMAIL: qi-001@outlook.com
  

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Python3.8
      uses: actions/setup-python@v2

    # Runs a single command using the runners shell
    - name: Setup Python environment
      run:  
        python -m pip install .

    - name: Run monitor checkout
      run: 
        python ./tests/test.py


   ## Runing push if possible
    - name: Set env of today
      run: echo "TODAY=$(date '%d/%m/%y')" >> $GITHUB_ENV

    - name: Push daily updates
      uses: github-actions-x/commit@v2.9
      with: 
        github-token: ${{secrets.GITHUB_TOKEN}}
        commit-message: "[update] today (${{env.TODAY}}) new pub"
        files: data/*
        rebase: 'true'
        name: ${{env.GITHUB_NAME}}
        email: ${{env.GITHUB_EMAIL}}


