# This is a basic workflow that is manually triggered

name: AutoMailor workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
    #schedule:
    ## '[min] [hour] [day] [month] [weekday]'
    #- cron: '0 * * * *'
      ## at the begin of every hour
   
env: 
  GITHUB_NAME: bon-qi
  GITHUB_EMAIL: qi-001@outlook.com

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  monitor:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Python3.8
      uses: actions/setup-python@v2
#      with: 
#	    python-version: 3.8

    # Runs a single command using the runners shell
    - name: Setup Python environment
      run: | 
        python -m pip install -r ./requirements.txt
        python -m pip install .

    - name: Run monitor checkout
      run: |
        python ./tests/test.py

#    - name: Push new updates
#      use: github-actions-x/commit@v2.9
#      with: 
#        github-token: ${{secrets.G_T}}
#        commit-message: "[update] today new pub"
#        files: tests/*
#        rebase: 'true'
#        name: ${{env.GITHUB_NAME}}
#        email: ${{env.GITHUB_EMAIL}}


